### ISSUE TITLE
Skipper panics if swarm port occupied at start

### ISSUE THREAD

**Issue by roffe** [zalando/skipper#1005]
**Describe the bug**
Skipper panics on requests if the swarm port is occupied on runtime

**To Reproduce**
Add context, for example:
1. enable swim clustering
2. occupie port on the host with f.x `nc -lp 9990`
3. start skipper with swarm (swim) ratelimiting

**Expected behavior**
magic

**Observed behavior**
ALB throws 502 when req comes in to Skipper.
In skipper logs:

```
[APP]time="2019-03-25T15:17:52Z" level=error msg="SWARM: failed to create memberlist: Could not set up network transport: Failed to start TCP listener on \"10.0.117.154\" port 9990: listen tcp 10.0.117.154:9990: bind: address already in use"
[APP]time="2019-03-25T15:17:52Z" level=error msg="failed to init swarm with options &{swarm:0 MaxMessageBuffer:4194304 LeaveTimeout:5s SwarmPort:9990 KubernetesOptions:0xc0000b85f0 StaticSwarm:<nil> FakeSwarm:false FakeSwarmLocalNode: Debug:false}: Could not set up network transport: Failed to start TCP listener on \"10.0.117.154\" port 9990: listen tcp 10.0.117.154:9990: bind: address already in use"
[APP]time="2019-03-25T15:20:32Z" level=error msg="swarm is nil"
2019/03/25 15:20:32 http: panic serving 10.0.114.193:38580: runtime error: invalid memory address or nil pointer dereference
goroutine 427 [running]:
net/http.(*conn).serve.func1(0xc000308fa0)
	/usr/local/go/src/net/http/server.go:1769 +0xc9
panic(0xdd5320, 0x17ba690)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/zalando/skipper/swarm.(*Swarm).broadcast(0x0, 0xc0004a9c80, 0xc0004a9c00, 0xc00038c080)
	/workspace/swarm/swarm.go:362 +0x34
github.com/zalando/skipper/swarm.(*Swarm).ShareValue(0x0, 0xc00052c840, 0x20, 0xd7cde0, 0xc00038c080, 0x0, 0x1)
	/workspace/swarm/swarm.go:383 +0x7f
github.com/zalando/skipper/ratelimit.(*clusterLimitSwim).Allow(0xc00029c320, 0xc00038c070, 0xc, 0xc)
	/workspace/ratelimit/swim.go:96 +0x23e
github.com/zalando/skipper/ratelimit.(*Ratelimit).Allow(...)
	/workspace/ratelimit/ratelimit.go:261
github.com/zalando/skipper/proxy.(*Proxy).checkRatelimit(0xc000494000, 0xc0004829a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/proxy/proxy.go:870 +0x3f3
github.com/zalando/skipper/proxy.(*Proxy).do(0xc000494000, 0xc0004829a0, 0xc0000adcb0, 0xc000494000)
	/workspace/proxy/proxy.go:959 +0x852
github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP(0xc000494000, 0x106f180, 0xc0004828c0, 0xc000168d00)
	/workspace/proxy/proxy.go:1196 +0x5de
net/http.serverHandler.ServeHTTP(0xc0001272b0, 0x106f180, 0xc0004828c0, 0xc000168c00)
	/usr/local/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc000308fa0, 0x1072e40, 0xc0004a9b00)
	/usr/local/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
[APP]time="2019-03-25T15:20:33Z" level=error msg="swarm is nil"
2019/03/25 15:20:33 http: panic serving 10.0.113.160:23248: runtime error: invalid memory address or nil pointer dereference
goroutine 400 [running]:
net/http.(*conn).serve.func1(0xc000352640)
	/usr/local/go/src/net/http/server.go:1769 +0xc9
panic(0xdd5320, 0x17ba690)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/zalando/skipper/swarm.(*Swarm).broadcast(0x0, 0xc0002a0c00, 0xc0004a9c00, 0xc0003dd9a8)
	/workspace/swarm/swarm.go:362 +0x34
github.com/zalando/skipper/swarm.(*Swarm).ShareValue(0x0, 0xc0004a5060, 0x20, 0xd7cde0, 0xc0003dd9a8, 0x0, 0x1)
	/workspace/swarm/swarm.go:383 +0x7f
github.com/zalando/skipper/ratelimit.(*clusterLimitSwim).Allow(0xc00029c320, 0xc0003dd9e0, 0xc, 0xc)
	/workspace/ratelimit/swim.go:96 +0x23e
github.com/zalando/skipper/ratelimit.(*Ratelimit).Allow(...)
	/workspace/ratelimit/ratelimit.go:261
github.com/zalando/skipper/proxy.(*Proxy).checkRatelimit(0xc000494000, 0xc0004948c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/proxy/proxy.go:870 +0x3f3
github.com/zalando/skipper/proxy.(*Proxy).do(0xc000494000, 0xc0004948c0, 0xc00072acb0, 0xc000494000)
	/workspace/proxy/proxy.go:959 +0x852
github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP(0xc000494000, 0x106f180, 0xc0004947e0, 0xc0001d6b00)
	/workspace/proxy/proxy.go:1196 +0x5de
net/http.serverHandler.ServeHTTP(0xc0001272b0, 0x106f180, 0xc0004947e0, 0xc0001d6a00)
	/usr/local/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc000352640, 0x1072e40, 0xc0002a0b00)
	/usr/local/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
[APP]time="2019-03-25T15:20:33Z" level=error msg="swarm is nil"
2019/03/25 15:20:33 http: panic serving 10.0.114.193:38586: runtime error: invalid memory address or nil pointer dereference
goroutine 431 [running]:
net/http.(*conn).serve.func1(0xc000309040)
	/usr/local/go/src/net/http/server.go:1769 +0xc9
panic(0xdd5320, 0x17ba690)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/zalando/skipper/swarm.(*Swarm).broadcast(0x0, 0xc0004a9e00, 0xc0004a9c00, 0xc00038c178)
	/workspace/swarm/swarm.go:362 +0x34
github.com/zalando/skipper/swarm.(*Swarm).ShareValue(0x0, 0xc00052c9c0, 0x20, 0xd7cde0, 0xc00038c178, 0x0, 0x1)
	/workspace/swarm/swarm.go:383 +0x7f
github.com/zalando/skipper/ratelimit.(*clusterLimitSwim).Allow(0xc00029c320, 0xc00038c1e0, 0xc, 0xc)
	/workspace/ratelimit/swim.go:96 +0x23e
github.com/zalando/skipper/ratelimit.(*Ratelimit).Allow(...)
	/workspace/ratelimit/ratelimit.go:261
github.com/zalando/skipper/proxy.(*Proxy).checkRatelimit(0xc000494000, 0xc000482b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/proxy/proxy.go:870 +0x3f3
github.com/zalando/skipper/proxy.(*Proxy).do(0xc000494000, 0xc000482b60, 0xc0000adcb0, 0xc000494000)
	/workspace/proxy/proxy.go:959 +0x852
github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP(0xc000494000, 0x106f180, 0xc000482a80, 0xc000168f00)
	/workspace/proxy/proxy.go:1196 +0x5de
net/http.serverHandler.ServeHTTP(0xc0001272b0, 0x106f180, 0xc000482a80, 0xc000168e00)
	/usr/local/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc000309040, 0x1072e40, 0xc0004a9cc0)
	/usr/local/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
[APP]time="2019-03-25T15:20:38Z" level=error msg="swarm is nil"
2019/03/25 15:20:38 http: panic serving 10.0.114.193:38600: runtime error: invalid memory address or nil pointer dereference
goroutine 459 [running]:
net/http.(*conn).serve.func1(0xc00015e0a0)
	/usr/local/go/src/net/http/server.go:1769 +0xc9
panic(0xdd5320, 0x17ba690)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/zalando/skipper/swarm.(*Swarm).broadcast(0x0, 0xc0000c65c0, 0xc0004a9c00, 0xc00038c0a8)
	/workspace/swarm/swarm.go:362 +0x34
github.com/zalando/skipper/swarm.(*Swarm).ShareValue(0x0, 0xc00013b060, 0x20, 0xd7cde0, 0xc00038c0a8, 0x0, 0x1)
	/workspace/swarm/swarm.go:383 +0x7f
github.com/zalando/skipper/ratelimit.(*clusterLimitSwim).Allow(0xc00029c320, 0xc00038c0e0, 0xc, 0xc)
	/workspace/ratelimit/swim.go:96 +0x23e
github.com/zalando/skipper/ratelimit.(*Ratelimit).Allow(...)
	/workspace/ratelimit/ratelimit.go:261
github.com/zalando/skipper/proxy.(*Proxy).checkRatelimit(0xc000494000, 0xc0004820e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/proxy/proxy.go:870 +0x3f3
github.com/zalando/skipper/proxy.(*Proxy).do(0xc000494000, 0xc0004820e0, 0xc00072ecb0, 0xc000494000)
	/workspace/proxy/proxy.go:959 +0x852
github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP(0xc000494000, 0x106f180, 0xc000482000, 0xc0001d6400)
	/workspace/proxy/proxy.go:1196 +0x5de
net/http.serverHandler.ServeHTTP(0xc0001272b0, 0x106f180, 0xc000482000, 0xc0001d6300)
	/usr/local/go/src/net/http/server.go:2774 +0xab
net/http.(*conn).serve(0xc00015e0a0, 0x1072e40, 0xc0000c6080)
	/usr/local/go/src/net/http/server.go:1878 +0x84c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
...
```

**Comment by szuecs** [comment]
Thanks @roffe , as already wrote in chat, please use the redis based cluster ratelimit in production.

**Comment by demonCoder95** [comment]
The bug comes from the way `Local()` is assumed to always return a valid `swarm` type pointer, which is not the case because `swarm` can be `nil`. 

What triggers this bug, [here](https://github.com/zalando/skipper/blob/master/swarm/swarm.go#L365), we have the usage in the form `Local().Name`. This has the problem when the `swarm` pointer is `nil`, the `Local()` function call returns `nil` and an attempt to dereference results in a panic, as this bug describes.

There are instances of this `Local().Name` in the control loop of the swarm, but there, it is not suspected that this panic can happen since before starting the control loop the swarm struct is well defined, and therefore, `s.Local()` is not `nil`.

This can be corrected by wrapping `Local().Name` in a check around the offending line.
