### ISSUE TITLE
Flush on upgraded connections lead to panic 

### ISSUE THREAD

**Issue by szuecs** [zalando/skipper#1564]
**Describe the bug**
Flush socket also in error cases [PR](https://github.com/zalando/skipper/pull/1560) result in panic as 
[commented](https://github.com/zalando/skipper/pull/1560#issuecomment-714710929).

The bug was introduced in https://github.com/zalando/skipper/releases/tag/v0.11.167

**To Reproduce**
backend
```
wscat -l 1234
listening on port 1234 (press CTRL+C to quit)
client connected
< asd
< asd
C-c
```

proxy
```
% bin/skipper -experimental-upgrade -inline-routes '* -> "http://localhost:1234"'
[APP]INFO[0000] Expose metrics in codahale format
[APP]INFO[0000] support listener on :9911
[APP]INFO[0000] route settings, reset, route: : * -> "http://localhost:1234"
[APP]INFO[0000] route settings received
[APP]INFO[0000] route settings applied
[APP]INFO[0000] proxy listener on :9090
[APP]INFO[0000] TLS settings not found, defaulting to HTTP
[APP]ERRO[0021] error proxying data from src to dst: read tcp 127.0.0.1:38202->127.0.0.1:1234: read: connection reset by peer
127.0.0.1 - - [23/Oct/2020:14:50:02 +0200] "GET / HTTP/1.1" 0 0 "-" "-" 8922 localhost:9090 - -
2020/10/23 14:50:11 http: response.WriteHeader on hijacked connection from github.com/zalando/skipper/logging.(*LoggingWriter).Flush (loggingwriter.go:39)
2020/10/23 14:50:11 http: panic serving 127.0.0.1:33576: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc000338140)
        /usr/share/go/src/net/http/server.go:1801 +0x147
panic(0x139ed20, 0x1df21f0)
        /usr/share/go/src/runtime/panic.go:975 +0x3e9
bufio.(*Writer).Flush(0x0, 0xc8, 0x7fb5481ae4a8)
        /usr/share/go/src/bufio/bufio.go:601 +0x26
net/http.(*response).Flush(0xc0003122a0)
        /usr/share/go/src/net/http/server.go:1673 +0x35
github.com/zalando/skipper/logging.(*LoggingWriter).Flush(...)
        /home/sszuecs/go/src/github.com/zalando/skipper/logging/loggingwriter.go:39
github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP.func2(0xc0000ebb60, 0xc0003121c0, 0xc0001881e0, 0xc0000ebc08)
        /home/sszuecs/go/src/github.com/zalando/skipper/proxy/proxy.go:1446 +0xe2
github.com/zalando/skipper/proxy.(*Proxy).ServeHTTP(0xc0003121c0, 0x1637fc0, 0xc0003122a0, 0xc0000f2d00)
        /home/sszuecs/go/src/github.com/zalando/skipper/proxy/proxy.go:1478 +0x609
net/http.serverHandler.ServeHTTP(0xc0001c4000, 0x1637fc0, 0xc0003122a0, 0xc0000f2c00)
        /usr/share/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000338140, 0x163b380, 0xc00033bdc0)
        /usr/share/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/share/go/src/net/http/server.go:2969 +0x36c
```

client
```
% wscat -c http://localhost:9090/              fix/error-path-response-body-flush
connected (press CTRL+C to quit)
> asd
> asd
< das
> asd
readline.js:1021
            throw err;
            ^

Error: not opened
    at WebSocket.send (/usr/local/lib/node_modules/wscat/node_modules/ws/lib/WebSocket.js:218:16)
    at Console.line (/usr/local/lib/node_modules/wscat/bin/wscat:203:10)
    at emitOne (events.js:116:13)
    at Console.emit (events.js:211:7)
    at Interface.line (/usr/local/lib/node_modules/wscat/bin/wscat:34:10)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._line (readline.js:631:8)
    at Interface._ttyWrite (readline.js:911:14)
zsh: exit 1     wscat -c http://localhost:9090/
```

**Expected behavior**
Do not panic

**Observed behavior**
Panics, but does not result in proxy not serving the request, nor getting unresponsive.
Websocket applications might observe errors on tear down of a connection.

**Comment by AlexanderYastrebov** [comment]
Judging from https://github.com/zalando/skipper/issues/1508 the problem might be observed by `kubectl exec` if skipper is a proxy in front of the kube-apiserver

**Comment by szuecs** [comment]
https://github.com/zalando/skipper/releases/tag/v0.11.172 contains a fix

@AlexanderYastrebov yes that's the case. Kubectl exec, port-forward, attach, log were impacted, but we I am pretty sure there is too few uses of these that these could impact anything.
