### ISSUE TITLE
error: endpoint not found

### ISSUE THREAD

**Issue by universam1** [zalando/skipper#1582]
**Describe the bug**
upgrading from version .150 to .179 breaks majority of routes, Skipper returns "no endpoint" when accessing these routes

**To Reproduce**

errors logged
```
[APP]time="2020-11-02T07:46:29Z" level=error msg="convertPathRule: add shuntroute to return 502 for ingress status/status service status with 0 endpoints: endpoint not found"
```

Slack ref: https://gophers.slack.com/archives/C82Q5JNH5/p1604304999030600

@szuecs

**Comment by szuecs** [comment]
@universam1 thanks.
The log is more information than a serious error. Do you see a significant increase of 502 in your metrics?

**Comment by universam1** [comment]
I can pinpoint the breaking change was introduced in version .174.
Actually with that version I even get a nil-pointer panic at this critical point!
```
msg="route settings, reset, route: kube_monitoring__alertmanager_main__monitoring_org___alertmanager__alertmanager_main:  │
│ %!v(PANIC=String method: runtime error: invalid memory address or nil pointer dereference)"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x788366]
goroutine 49 [running]:
github.com/zalando/skipper/routing.createFilter(0xc000285860, 0x0, 0xc000342d50, 0x2, 0x3, 0xc00017e2e0, 0x2)
    /workspace/routing/datasource.go:221 +0x26
github.com/zalando/skipper/routing.createFilters(0xc000285860, 0xc0003421b0, 0x5, 0x6, 0xc000342d50, 0x0, 0x0, 0x0, 0x0, 0xc0002dfb10)
    /workspace/routing/datasource.go:242 +0x9f
github.com/zalando/skipper/routing.processRouteDef(0xc000342d50, 0xc000285860, 0xc000338a20, 0x1, 0x2, 0xc0003221c0)
    /workspace/routing/datasource.go:465 +0xd0
github.com/zalando/skipper/routing.processRouteDefs(0xc000285860, 0x0, 0xb2d05e00, 0xc00027eb70, 0x1, 0x1, 0xc000260900, 0x11, 0x12, 0x20, ...)
    /workspace/routing/datasource.go:502 +0x105
github.com/zalando/skipper/routing.receiveRouteMatcher(0xc000285860, 0x0, 0xb2d05e00, 0xc00027eb70, 0x1, 0x1, 0xc000260900, 0x11, 0x12, 0x20, ...)
    /workspace/routing/datasource.go:539 +0x345
created by github.com/zalando/skipper/routing.(*Routing).startReceivingUpdates
    /workspace/routing/routing.go:334 +0xa9
```

**Comment by universam1** [comment]
related to #1525

**Comment by szuecs** [comment]
also related https://github.com/zalando/skipper/pull/1569 (fixed the panic)

**Comment by szuecs** [comment]
Thanks to @universam1 for the investigation.

Chat transcript:
```
Samuel Lang  17:04
Found the issue/bug @sszuecs -  did some massive debugging live cluster - its a tricky one :slightly_smiling_face:consider this service definition:

spec:
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web

it fails here: https://github.com/zalando/skipper/blob/master/dataclients/kubernetes/ingressdefinitions.go#L85

if port.Name == svcPortName || strconv.Itoa(port.Port) == svcPortTarget 

because the parsing is flawed!
The above service is parsed following way:

port.Name: "web"
svcPortName: "9093"
strconv.Itoa(port.Port): "9093"
svcPortTarget: "web"

As you can see the svcPortName is mixed up of the name vs port-numberr, hence the test does always fail!cc @Sean Escriva
dataclients/kubernetes/ingressdefinitions.go:85

            if port.Name == svcPortName || strconv.Itoa(port.Port) == svcPortTarget {

<https://github.com/zalando/skipper|zalando/skipper>zalando/skipper | Added by GitHub
Sean Escriva  17:10
Wow, very interesting
Samuel Lang  17:16
same is true for the other failing service, see my log outputs:

    msg="targets: port: {http 80 TCP}"                                                                    
    msg="FAILING: port.Name: 'http' == svcPortName: '80' || strconv.Itoa(port.Port): '80' == svcPortTarget: 'http' "                                                                                                                                          
    msg="convertPathRule: Found 0 endpoints 'http' for 'jwtdebug'"

Samuel Lang  17:22
with other words, we need some unit tests to verify the parsing of more complex service spec definitions using names. Probably the service name convention of http did cover a bug
```

We work on a fix

**Comment by szuecs** [comment]
@universam1 can you test registry.opensource.zalan.do/pathfinder/skipper-test:pr-1584-2 please?

**Comment by universam1** [comment]
> @universam1 can you test registry.opensource.zalan.do/pathfinder/skipper-test:pr-1584-2 please?

Wonderful - I've tested it against .179 and I can confirm in lab at least that fix does solve our issue
