### ISSUE TITLE
Flaky TestAuthorizeRequestFilter/Simple_Forbidden

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/skipper#2962]
https://github.com/zalando/skipper/actions/runs/8112262572/job/22173104338?pr=2885

```
2024/03/01 13:43:40 http: panic serving 127.0.0.1:40776: Fail in goroutine after TestAuthorizeRequestFilter/Simple_Forbidden has completed
goroutine 321 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:1898 +0xbe
panic({0x1caf320?, 0xc0009b9560?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770 +0x132
testing.(*common).Fail(0xc0003a2820)
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:952 +0xd4
testing.(*common).Errorf(0xc0003a2820, {0x1fa3054?, 0xc28985?}, {0xc0009b9520?, 0x1cafb60?, 0x301?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1075 +0x5e
github.com/stretchr/testify/assert.Fail({0x2215c00, 0xc0003a2820}, {0xc0000f61e0, 0x91}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:333 +0x370
github.com/stretchr/testify/assert.Equal({0x2215c00, 0xc0003a2820}, {0x1caf320, 0xc0009b93e0}, {0x1caf320, 0x2f6a980}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:417 +0x2ed
github.com/zalando/skipper/filters/openpolicyagent/opaauthorizerequest.TestAuthorizeRequestFilter.func1.1({0x22260f0, 0xc00075a0e0}, 0xc000715c20)
	/home/runner/work/skipper/skipper/filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go:269 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc8eb19?, {0x22260f0?, 0xc00075a0e0?}, 0xc0006b5b68?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0xc0008d0e70?}, {0x22260f0?, 0xc00075a0e0?}, 0x6?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0008c6fc0, {0x222aa10, 0xc0003fe630})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 81
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3285 +0x4b4
2024/03/01 13:43:40 http: panic serving 127.0.0.1:40782: Fail in goroutine after TestAuthorizeRequestFilter/Simple_Forbidden has completed
goroutine 362 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:1898 +0xbe
panic({0x1caf320?, 0xc000c2e7f0?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770 +0x132
testing.(*common).Fail(0xc0003a2820)
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:952 +0xd4
testing.(*common).Errorf(0xc0003a2820, {0x1fa3054?, 0xc28985?}, {0xc000c2e7b0?, 0x1cafb60?, 0x301?})
	/opt/hostedtoolcache/go/1.22.0/x64/src/testing/testing.go:1075 +0x5e
github.com/stretchr/testify/assert.Fail({0x2215c00, 0xc0003a2820}, {0xc0000e2750, 0x8d}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:333 +0x370
github.com/stretchr/testify/assert.Equal({0x2215c00, 0xc0003a2820}, {0x1caf320, 0xc000c2e680}, {0x1caf320, 0x2f6a980}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.8.4/assert/assertions.go:417 +0x2ed
github.com/zalando/skipper/filters/openpolicyagent/opaauthorizerequest.TestAuthorizeRequestFilter.func1.1({0x22260f0, 0xc0009d2000}, 0xc000b6f0e0)
	/home/runner/work/skipper/skipper/filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go:269 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc8eb19?, {0x22260f0?, 0xc0009d2000?}, 0xc0006b3b68?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0xc000c29b90?}, {0x22260f0?, 0xc0009d2000?}, 0x6?)
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0009ae000, {0x222aa10, 0xc0003fe630})
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 81
	/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3285 +0x4b4
--- FAIL: TestAuthorizeRequestFilter (1.56s)
    assertions.go:333: 
        	Error Trace:	/home/runner/work/skipper/skipper/filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go:269
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2166
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3137
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2039
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/asm_amd64.s:1695
        	Error:      	Not equal: 
        	            	expected: "{ \"target_id\" / \"wrong id\" }"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-{ "target_id" / "wrong id" }
        	            	+
        	Test:       	TestAuthorizeRequestFilter/Simple_Forbidden
    assertions.go:333: 
        	Error Trace:	/home/runner/work/skipper/skipper/filters/openpolicyagent/opaauthorizerequest/opaauthorizerequest_test.go:269
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2166
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:3137
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/net/http/server.go:2039
        	            				/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/asm_amd64.s:1695
        	Error:      	Not equal: 
        	            	expected: "{ \"target_id\" : \"123456\" }"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-{ "target_id" : "123456" }
        	            	+
        	Test:       	TestAuthorizeRequestFilter/Simple_Forbidden
FAIL
FAIL	github.com/zalando/skipper/filters/openpolicyagent/opaauthorizerequest	1.577s
```

**Comment by AlexanderYastrebov** [comment]
@mjungsbluth FYI

**Comment by mjungsbluth** [comment]
@AlexanderYastrebov will have a look why that is the case…

**Comment by mjungsbluth** [comment]
@AlexanderYastrebov I actually have a hard time reproducing this locally. The issue is that requests that are initiated from one test are received by another test's `httptest.Server` which I don't think should happen due to isolated ports. 

What was missing is a `Close()` on the http servers in the test so that might yield a race condition but I don't have enough experience with `httptest` in these kinds of tests to see if this is actually something that is possible. 

Have you seen this problem in other projects?

**Comment by AlexanderYastrebov** [comment]
@mjungsbluth I did not see such issue before and did not look into this one either. Lets have your #2993 and see if it helps.

**Comment by AlexanderYastrebov** [comment]
Closing for now, will reopen if reapperas
